### ISSUE TITLE
add success stories to section 1

### ISSUE THREAD

**Issue by BonnieJRobert** [bcgov/ds-intro-to-git#14]
If there's time, one thing we might want to add here is success stories from within BC Stats - projects that have used/currently use VC in some fashion to make their lives easier (people always want examples of past work).

Some ideas might be:

Using GitHub to share code to more quickly produce some NLP code for the demographic survey.
Using GitHub to store code for the Small Business Dashboard that will need to be updated annually
Metadata viewer
Using GitLab in the SRE to sync and collaborate across teams/projects

**Comment by stephhazlitt** [comment]
Completed with testimonial.
